In [38]:
#importing libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier, IsolationForest

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

In [31]:
#uploading the dataset
from google.colab import files

uploaded = files.upload()

Saving creditcard.csv to creditcard (1).csv

In [39]:
#reading the dataset
df = pd.read_csv("creditcard.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB
None

In [10]:
#for supervised learning we have to remove null rows
#Finding the incomplete row
print("Missing values:")
print(df.isnull().sum().sum())

Missing values:
0

In [36]:
#classifying how many fraud and how many are legitimate
#class=0--> legitimate
#class=1--> fraud
print("Class distribution:")
print(df["Class"].value_counts())

Class distribution:
Class
0    284315
1       492
Name: count, dtype: int64

In [12]:
#Calculating the class percentages
print("Class percentage:")
print(df["Class"].value_counts(normalize=True) * 100)      # this will detect class imbalance

Class percentage:
Class
0    99.827251
1     0.172749
Name: proportion, dtype: float64

In [14]:
#Separating the features and the target
X = df.drop("Class", axis=1)
y = df["Class"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (284807, 30)
y shape: (284807,)

In [15]:
# now Training/test spliting
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\ny_train:")
print(y_train.value_counts())

print("\ny_test:")
print(y_test.value_counts())

X_train: (227845, 30)
X_test: (56962, 30)

y_train:
Class
0    227451
1       394
Name: count, dtype: int64

y_test:
Class
0    56864
1       98
Name: count, dtype: int64

In [16]:
#now Scaling  Time and Amount
scaler = StandardScaler()

X_train = X_train.copy()
X_test = X_test.copy()

X_train[["Time", "Amount"]] = scaler.fit_transform(
    X_train[["Time", "Amount"]]
)

X_test[["Time", "Amount"]] = scaler.transform(
    X_test[["Time", "Amount"]]
)

In [17]:
X_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
265518,1.411588,1.946747,-0.752526,-1.355130,-0.661630,1.502822,4.024933,-1.479661,1.139880,1.406819,...,-0.134435,0.076197,0.297537,0.307915,0.690980,-0.350316,-0.388907,0.077641,-0.032248,-0.322494
180305,0.623141,2.035149,-0.048880,-3.058693,0.247945,2.943487,3.298697,-0.002192,0.674782,0.045826,...,-0.227279,0.038628,0.228197,0.035542,0.707090,0.512885,-0.471198,0.002520,-0.069002,-0.339764
42664,-1.130680,-0.991920,0.603193,0.711976,-0.992425,-0.825838,1.956261,-2.212603,-5.037523,0.000772,...,1.280856,-2.798352,0.109526,-0.436530,-0.932803,0.826684,0.913773,0.038049,0.185340,0.346693
198723,0.794699,2.285718,-1.500239,-0.747565,-1.668119,-1.394143,-0.350339,-1.427984,0.010010,-1.118447,...,-0.490642,-0.139670,0.077013,0.208310,-0.538236,-0.278032,-0.162068,0.018045,-0.063005,-0.327360
82325,-0.748102,-0.448747,-1.011440,0.115903,-3.454854,0.715771,-0.147490,0.504347,-0.113817,-0.044782,...,-0.275297,-0.243245,-0.173298,-0.006692,-1.362383,-0.292234,-0.144622,-0.032580,-0.064194,-0.008281

In [19]:
#supervised model
#Training Random Forest
rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest training completed.")

Random Forest training completed.

In [20]:
#Generating predictions
y_pred = rf_model.predict(X_test)

y_prob = rf_model.predict_proba(X_test)[:, 1]

print("y_pred:", len(y_pred))
print("y_prob:", len(y_prob))

y_pred: 56962
y_prob: 56962

In [21]:
#calculating Precision, Recall, F1 and PR-AUC
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
pr_auc = average_precision_score(y_test, y_prob)

print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)
print("PR-AUC    :", pr_auc)

Precision : 0.9605263157894737
Recall    : 0.7448979591836735
F1 Score  : 0.8390804597701149
PR-AUC    : 0.8541999432510914

In [22]:
# this is the Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.96      0.74      0.84        98

    accuracy                           1.00     56962
   macro avg       0.98      0.87      0.92     56962
weighted avg       1.00      1.00      1.00     56962

In [25]:
#unsupervised anomaly detection
#Training Isolation Forest
iso_model = IsolationForest(
    n_estimators=100,
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso_model.fit(X_train)

print("Isolation Forest training completed.")

Isolation Forest training completed.

In [26]:
#Generating Predictions
iso_raw_pred = iso_model.predict(X_test)

# Isolation Forest:
# -1 = anomaly
#  1 = normal
# Convert to:
#  1 = fraud/anomaly
#  0 = normal

iso_pred = np.where(iso_raw_pred == -1, 1, 0)

print("Isolation Forest predictions generated.")
print(pd.Series(iso_pred).value_counts())

Isolation Forest predictions generated.
0    54994
1     1968
Name: count, dtype: int64

In [27]:
#Generating Anomaly Scores
iso_scores = -iso_model.decision_function(X_test)

print("Anomaly scores generated.")
print(iso_scores[:10])

Anomaly scores generated.
[-0.09785723 -0.0270454   0.03376484 -0.14507207 -0.04435583 -0.13335219
 -0.10009845 -0.12768267 -0.13314031 -0.1300492 ]

In [29]:
#Evaluating Isolation Forest
iso_precision = precision_score(y_test, iso_pred, zero_division=0)
iso_recall = recall_score(y_test, iso_pred, zero_division=0)
iso_f1 = f1_score(y_test, iso_pred, zero_division=0)
iso_pr_auc = average_precision_score(y_test, iso_scores)

print("Isolation Forest")
print("----------------")
print("Precision :", iso_precision)
print("Recall    :", iso_recall)
print("F1 Score  :", iso_f1)
print("PR-AUC    :", iso_pr_auc)

Isolation Forest
----------------
Precision : 0.04217479674796748
Recall    : 0.8469387755102041
F1 Score  : 0.0803484995159729
PR-AUC    : 0.21797227754191925

In [30]:
#Comparing Both Models
#Creating comparison table
results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Isolation Forest"
    ],
    "Precision": [
        precision,
        iso_precision
    ],
    "Recall": [
        recall,
        iso_recall
    ],
    "F1 Score": [
        f1,
        iso_f1
    ],
    "PR-AUC": [
        pr_auc,
        iso_pr_auc
    ]
})

results

              Model  Precision    Recall  F1 Score    PR-AUC
0     Random Forest   0.960526  0.744898  0.839080  0.854200
1  Isolation Forest   0.042175  0.846939  0.080348  0.217972

In [33]:
#now saving the results
results.to_csv("model_comparison.csv", index=False)

print("Model comparison saved successfully.")

Model comparison saved successfully.

In [34]:
#via this downloading this result
from google.colab import files

files.download("model_comparison.csv")